### ISSUE TITLE
v1 tag is not updated

### ISSUE THREAD

**Issue by saliceti** [Azure/use-kubelogin#50]
We pinned the action to the v1 tag and hoped to receive the minor updates automatically. But the v1 tag was not updated and still points to an old commit.

As per the [Github actions documentation](https://docs.github.com/en/actions/creating-actions/about-custom-actions#using-tags-for-release-management), v1 should be updated to point at the same commit as v1.2.

**Comment by bcho** [comment]
Hi thanks for reporting this. But unfortunately since v1 tag has been made before, and seems like creating a new v1 branch pointing to v1.2 after this will not trigger the auto bump neither, I think we cannot do much here. I think we can start with the new floating branch practice for major version in v2. Will that work for you? @saliceti

**Comment by saliceti** [comment]
Implementing the automatic tag update from v2 would be great. Can the v1 tag be updated manually in the meantime?

**Comment by sheeeng** [comment]
@saliceti, does the following work as a workaround for you?

```yaml
- uses: azure/use-kubelogin@76597ae0fcbaace21b05e13a2cbf8daee2c6e820 # v1.2
```

**Comment by saliceti** [comment]
@sheeeng this should work. But I can already get `v1.2` by using `@v1.2`. And this points at 76597ae0fcbaace21b05e13a2cbf8daee2c6e820.

Thi issue is about the `v1` tag which still points at e1a8161c479fd5debcdec63db9a2c29f52ce6f5e. It should be updated and point at the same commit as `v1.2`, ie 76597ae0fcbaace21b05e13a2cbf8daee2c6e820.

**Comment by f2calv** [comment]
Agree with @saliceti here - this is fundamentally how github actions versioning is intended to work, floating tags on major versions are the mainstay.

i.e. for example when publishing v1.3;

- Automatically move the v1 tag to the same commit with majorVersion == 1, i.e. v1
- Automatically move the v1.3 tag to the same commit with majorVersion ==1 && minorVersion 2, i.e. v1.3
- Create a new tag with v1.3.xxx tag for the newest version

**Comment by julie-ng** [comment]
> Hi thanks for reporting this. But unfortunately since v1 tag has been made before, and seems like creating a new v1 branch pointing to v1.2 after this will not trigger the auto bump neither, I think we cannot do much here. I think we can start with the new floating branch practice for major version in v2. Will that work for you? @saliceti

@bcho - v1 should be a tag, not a branch, no? After v1.x is released, you need to force push the v1 tag, which is documented here https://github.com/actions/toolkit/blob/master/docs/action-versioning.md 

p.s. I stumbled on this looking for an official kubelogin action to do the _actual login_. Shame this one only installs it.

**Comment by bcho** [comment]
hey all, thanks for the suggestions, i have put the v1 tag to the commit of v1.2 . I will document this process a bit in the release steps doc.

From supply chain security perspective, I don't buy in on using a floating version in your infrastructure, especially for a component that will have access to your login credentials secrets. Giving dependabot already has support for pinning a version in your github actions, i would suggest to pin a specific version / commit to avoid surprise from upstream.


--------------

@julie-ng there are many ways for using kubelogin to do the *actual* login, hence, this actions helps the user to download the binary and let user to do the *actual* thing. From functional perspective, I see nothing this actions should be *shame* of :)
