### ISSUE TITLE
Node 16 deprecated and shows warnings on actions

### ISSUE THREAD

**Issue by eikooc** [Azure/use-kubelogin#9]
[Node 16 has reached End of Life (EoL)](https://nodejs.org/en/blog/announcements/nodejs16-eol)

Github supports node version 20 and we should move to use that instead

https://github.com/Azure/login/blob/45c3280904d6ab9d2fba45123b9e0aeb15ea9cd0/action.yml#L41

**Comment by bcho** [comment]
Bumped a new version v1.2 with your change, please have a try!
